spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    config:
      uri: http://config-server:8081

server:
  port: 443

eureka:
  client:
    service-url:
      defaultZone: http://eureka-sv:8761/eureka
