spring:
  application:
    name: sales-service

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

  cloud:
    config:
      uri: http://config-server:8081

eureka:
  client:
    service-url:
      defaultZone: http://eureka-sv:8761/eureka

server:
  port: 8086
